tasks:
  - name: vcpkg
    env:
      VCPKG_INSTALLATION_ROOT: /opt/vcpkg
    init: |
      sudo apt-get install ninja-build
      git clone https://github.com/Microsoft/vcpkg.git /tmp/vcpkg
      /tmp/vcpkg/bootstrap-vcpkg.sh
      /tmp/vcpkg/vcpkg install

vscode:
  extensions:
    - "llvm-vs-code-extensions.vscode-clangd"
    - "ms-vscode.cmake-tools"
    - "wayou.vscode-todo-highlight"
