trigger:
- master

jobs:
  - job: Windows_Build
    pool:
      vmImage: 'windows-2019'
    strategy:
      matrix:
        x86_debug:
          buildPlatform: 'x86'
          buildConfiguration: 'Debug'
        x86_release:
          buildPlatform: 'x86'
          buildConfiguration: 'Release'
        x64_debug:
          buildPlatform: 'x64'
          buildConfiguration: 'Debug'
        x64_release:
          buildPlatform: 'x64'
          buildConfiguration: 'Release'

    steps:
    - script: py -3 tools\win_build.py -a $(buildPlatform) -c $(buildConfiguration)

    - task: CopyFiles@2
      inputs:
        contents: '**\$(buildConfiguration)\**\?(*.exe|*.dll|*.pdb)'
        targetFolder: '$(build.artifactStagingDirectory)'

    - task: PublishBuildArtifacts@1
      inputs:
        pathToPublish: '$(build.artifactStagingDirectory)'
        artifactName: 'executables_$(buildPlatform)_$(buildConfiguration)'
