name: CI

on:
  push:
    branches: [master]
    paths-ignore:
      - "docs/**"
      - "drafts/**"
      - "**/README.md"
  pull_request:
    branches: [master]
    paths-ignore:
      - "docs/**"
      - "drafts/**"
      - "**/README.md"

jobs:
  build:
    name: Build
    runs-on: windows-latest
    strategy:
      matrix:
        buildConfiguration: [Debug, Release]
        architecture: [x86, x64]
        include:
          - architecture: x86
            triplet: x86-windows
          - architecture: x64
            triplet: x64-windows
      fail-fast: true

    env:
      vcpkgPackages: "gtest fmt ms-gsl"

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Restore artifacts, or run vcpkg, build and cache artifacts
        uses: lukka/run-vcpkg@v3
        id: runvcpkg
        with:
          vcpkgArguments: "${{ env.vcpkgPackages }}"
          vcpkgTriplet: "${{ matrix.triplet }}"

      - name: Run build script
        run: python tools\win_build.py -a ${{ matrix.architecture }} -c ${{ matrix.buildConfiguration }} --skip-install-packages
