name: CI

on:
  push:
    branches: [main, dev]
    paths-ignore:
      - "docs/**"
      - "**/README.md"
  pull_request:
    branches: [main, dev]
    paths-ignore:
      - "docs/**"
      - "**/README.md"

jobs:
  macos-build:
    name: macOS Build
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v7
        with:
          submodules: true

      - name: Install Libraries
        run: |
          brew install icu4c cairo pango sdl3

      - name: Build And Test (Static Linking)
        run: |
          cmake --workflow --preset ci-default

      - name: Build And Test (Dynamic Linking)
        run: |
          cmake --workflow --preset ci-dylib

  windows-build:
    name: Windows Build
    runs-on: windows-latest
    env:
      VCPKG_DEFAULT_BINARY_CACHE: ${{ github.workspace }}\.cache\vcpkg\archives

    steps:
      - uses: actions/checkout@v7
        with:
          submodules: true

      - name: Cache vcpkg
        uses: actions/cache@v6
        with:
          path: ${{ env.VCPKG_DEFAULT_BINARY_CACHE }}
          key: vcpkg-${{ runner.os }}-${{ github.run_id }}
          restore-keys: vcpkg-${{ runner.os }}-

      - name: Install Libraries
        working-directory: ./vcpkg
        run: |
          New-Item -ItemType Directory -Force -Path "$env:VCPKG_DEFAULT_BINARY_CACHE"
          .\bootstrap-vcpkg.bat
          .\vcpkg install icu sdl3

      - name: Build And Test (Static Linking)
        run: |
          . scripts/Use-VC.ps1
          Use-VC
          cmake --workflow --preset ci-default

      - name: Build And Test (Dynamic Linking)
        run: |
          . scripts/Use-VC.ps1
          Use-VC
          cmake --workflow --preset ci-dylib

  linux-build:
    name: Linux Build
    runs-on: ubuntu-26.04

    steps:
      - uses: actions/checkout@v7
        with:
          submodules: true

      - name: Install Libraries
        run: |
          sudo apt update
          sudo apt install -y libicu-dev libpng-dev libcairo2-dev libpango1.0-dev \
            libxcb1-dev libxcb-cursor-dev libxkbcommon-dev libxcb-imdkit-dev libxkbcommon-x11-dev \
            libsdl3-dev

      - name: Build And Test (Static Linking)
        run: |
          cmake --workflow --preset ci-default

      - name: Build And Test (Dynamic Linking)
        run: |
          cmake --workflow --preset ci-dylib
