name: CI

on:
  push:
    branches: [master]
    paths-ignore:
      - "docs/**"
      - "drafts/**"
      - "**/README.md"
  pull_request:
    branches: [master]
    paths-ignore:
      - "docs/**"
      - "drafts/**"
      - "**/README.md"

jobs:
  build:
    name: Build
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Restore Cache
        uses: actions/cache@v2
        with:
          path: ~/AppData/Local/vcpkg/archives
          key: vcpkg-${{ runner.os }}

      - name: Setup Ninja
        uses: ashutoshvarma/setup-ninja@master
        with:
          version: 1.10.2

      - name: Run build script
        shell: pwsh
        run: |
          . ./tools/Use-VC.ps1
          Use-VC
          mkdir build && cd build
          cmake .. -G Ninja -DCMAKE_BUILD_TYPE:STRING=Debug
          ninja all
