name: CI

on:
  push:
    branches: [master]
    paths-ignore:
      - "docs/**"
      - "drafts/**"
      - "**/README.md"
  pull_request:
    branches: [master]
    paths-ignore:
      - "docs/**"
      - "drafts/**"
      - "**/README.md"

env:
  VCPKG_FEATURE_FLAGS: manifests

jobs:
  build:
    name: Build
    runs-on: windows-latest
    strategy:
      matrix:
        buildConfiguration: [Debug, Release]
        architecture: [x86, x64]

    steps:
      - uses: actions/checkout@v2

      - name: Restore Cache
        uses: actions/cache@v2
        with:
          path: ~/AppData/Local/vcpkg/archives
          key: vcpkg-${{ runner.os }}

      - name: Run build script
        run: python tools\win_build.py -a ${{ matrix.architecture }} -c ${{ matrix.buildConfiguration }}
