name: CI

on:
  push:
    branches: [main]
    paths-ignore:
      - "docs/**"
      - "**/README.md"
  pull_request:
    branches: [main]
    paths-ignore:
      - "docs/**"
      - "**/README.md"

env:
  VCPKG_DEFAULT_BINARY_CACHE: /tmp/vcpkg-cache

jobs:
  macos-build:
    name: macOS Build
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Restore Cache
        uses: actions/cache@v2
        with:
          path: /tmp/vcpkg-cache
          key: vcpkg-${{ runner.os }}

      - name: Setup Ninja
        uses: ashutoshvarma/setup-ninja@master
        with:
          version: 1.10.2

      - name: Build
        run: |
          cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_C_COMPILER=/usr/bin/clang -DCMAKE_CXX_COMPILER=/usr/bin/clang++ -S. -Bbuild -G Ninja
          cmake --build build --config Debug --target all

      - name: Test
        working-directory: build
        run: |
          ctest -C Debug -T test --output-on-failure

  windows-build:
    name: Windows Build
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Restore Cache
        uses: actions/cache@v2
        with:
          path: /tmp/vcpkg-cache
          key: vcpkg-${{ runner.os }}

      - name: Setup Ninja
        uses: ashutoshvarma/setup-ninja@master
        with:
          version: 1.10.2

      - name: Build
        run: |
          cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -S. -Bbuild -G Ninja
          cmake --build build --config Debug --target all

      - name: Test
        working-directory: build
        run: |
          ctest -C Debug -T test --output-on-failure
